version: '3.8'


services:
  flask:
    container_name: "eoh_flask"
    image: flask:latest
    environment:
      EOH_NAME: "EarthObservationHub"
      EOH_IP: "localhost"
    restart: unless-stopped
    build:
      # build the image from Dockerfile
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    ports:
      # bind on our 5000 port because most people have 80, 8080 already bound
      - "5000:5000"
    depends_on:
      - postgres

  postgres:
    container_name: eoh_db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 1234
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 20

  adminer:
    container_name: eoh_adminer
    image: adminer:latest
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

# volumes definition here
volumes:
  # just a persistance data
  mysql-data:
    driver: local